export const products = [
  {
    id: "1",
    title: " Sitting Robot Mechanic",
    price: "€250,00",
    category: "Sculptures",
    dimensions: "12cm x 25cm x 12cm",
    weight: "1kg",
    materials: ["Car Engine Parts", "Pistions", "Beer opener"],
    description:
      "This sitting robot sculpture is a one-of-a-kind creation that merges industrial artistry with whimsy. Crafted entirely from upcycled car scrap parts and a functional beer opener, it embodies a perfect balance of form and function. The intricate design features meticulously arranged chains, pistons, and engine components, giving the robot a lifelike and dynamic appearance. The beer opener adds a playful touch, making it not just a captivating decorative piece but also a practical addition to any space. This sculpture is a testament to creativity and sustainability, breathing new life into discarded materials.",
    images: [
      "/robotSit1.jpg",
      "/robotSit2.jpg",
      "/robotSit3.jpg",
      "/robotSit4.jpg",
      "/robotSit5.jpg",
    ],
  },
  {
    id: "2",
    title: "Ashtray Robot Terminator",
    price: "€270,00",
    category: "Sculptures",
    dimensions: "12cm x 25cm x 12cm",
    weight: "1kg",
    materials: ["Car Engine Parts", "Pistions", "Chains"],
    description:
      "A majestic eagle sculpture crafted from various car engine components. The wings are made from carefully arranged transmission parts, while the body features intricate details created from smaller engine components. This piece symbolizes freedom and mechanical precision.",
    images: [
      "/ashtray1.jpg",
      "/ashtray2.jpg",
      "/ashtray3.jpg",
      "/ashtray4.jpg",
    ],
  },
  {
    id: "3",
    title: "Handmade Piston Gun Soldier",
    price: "€380,00",
    category: "Sculptures",
    dimensions: "12cm x 25cm x 12cm",
    weight: "1kg",
    materials: ["Car Engine Parts", "Pistions", "Gears"],
    description:
      "A majestic eagle sculpture crafted from various car engine components. The wings are made from carefully arranged transmission parts, while the body features intricate details created from smaller engine components. This piece symbolizes freedom and mechanical precision.",
    images: [
      "/gun1.jpg",
      "/gun2.jpg",
      "/gun3.jpg",
      "/gun4.jpg",
      "/gun5.jpg",
      "/gun6.jpg",
    ],
  },
  {
    id: "4",
    title: "Handmade Female Body",
    price: "€770,00",
    category: "Sculptures",
    dimensions: "12cm x 25cm x 12cm",
    weight: "1kg",
    materials: ["Car Engine Parts", "Pistions", "Metal"],
    description:
      "A majestic eagle sculpture crafted from various car engine components. The wings are made from carefully arranged transmission parts, while the body features intricate details created from smaller engine components. This piece symbolizes freedom and mechanical precision.",
    images: ["/body1.jpg", "/body2.jpg", "/body3.jpg"],
  },
  {
    id: "5",
    title: "Functional Electric Guitar",
    price: "€2000,00",
    category: "Sculptures",
    dimensions: "12cm x 25cm x 12cm",
    weight: "1kg",
    materials: ["Car Engine Parts", "Pistions", "Chains"],
    description:
      "A majestic eagle sculpture crafted from various car engine components. The wings are made from carefully arranged transmission parts, while the body features intricate details created from smaller engine components. This piece symbolizes freedom and mechanical precision.",
    images: [
      "/eGuitar1.jpg",
      "/eGuitar2.jpg",
      "/eGuitar3.jpg",
      "/eGuitar4.jpg",
      "/eGuitar5.jpg",
    ],
  },
  {
    id: "6",
    title: "Handmade Decorative Guitar",
    price: "€900,00",
    category: "Sculptures",
    dimensions: "12cm x 25cm x 12cm",
    weight: "1kg",
    materials: ["Car Engine Parts", "Pistions", "Chains"],
    description:
      "A majestic eagle sculpture crafted from various car engine components. The wings are made from carefully arranged transmission parts, while the body features intricate details created from smaller engine components. This piece symbolizes freedom and mechanical precision.",
    images: ["/guitar1.jpg", "/guitar2.jpg", "/guitar3.jpg", "/guitar4.jpg"],
  },
];

export const exhibitions = [
  {
    id: 1,
    title: "London Gallery",
    place: "London, UK",
    date: "04.01.2025",
    img: "/london.webp",
  },
  {
    id: 2,
    title: "Berlin Art Gallery",
    place: "Berlin, DE",
    date: "11.01.2025",
    img: "/berlin.jpg",
  },
  {
    id: 3,
    title: "Paris Art Gallery",
    place: "Paris, FR",
    date: "18.01.2025",
    img: "/paris.jpg",
  },
  {
    id: 4,
    title: "New York Art Gallery",
    place: "New York, USA",
    date: "25.01.2025",
    img: "/ny.webp",
  },
  {
    id: 5,
    title: "Istanbul Art Gallery",
    place: "Istanbul, TR",
    date: "02.02.2025",
    img: "/istanbul.webp",
  },
  {
    id: 6,
    title: "Sofia Art Gallery",
    place: "Sofia, BG",
    date: "09.02.2025",
    img: "/sofia.jpeg",
  },
];
